/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gskj_ffmpegtest_MainActivity */

#ifndef _Included_com_gskj_ffmpegtest_MainActivity
#define _Included_com_gskj_ffmpegtest_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gskj_ffmpegtest_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gskj_ffmpegtest_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_gskj_ffmpegtest_MainActivity
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_gskj_ffmpegtest_MainActivity_decode
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
